### ISSUE TITLE
Establish computational executions and data transfer from the SMILES gateway.

### ISSUE THREAD

**Issue by eroma2014** [GT-Nexus/SMILES#12]
- [ ] Goal 1: [Identify SMILES-related applications for the gateway deployment. ](https://github.com/GT-ARTISAN/SMILES/issues/13)
- [ ] Goal 2: [Add SMILES-related applications (e.g., Gaussian) into the gateway portal. ](https://github.com/GT-ARTISAN/SMILES/issues/14)
- [ ] Goal 3: [Configure computational resources to run computations through the gateway portal. ](https://github.com/GT-ARTISAN/SMILES/issues/15)
- [ ] Goal 4: [Enable computational executions through the SMILES CI web gateway portal. ](https://github.com/GT-ARTISAN/SMILES/issues/16)
