### ISSUE TITLE
Previous older data extraction from legacy databases and gateway executions.

### ISSUE THREAD

**Issue by eroma2014** [GT-Nexus/SMILES#17]
- [ ] Goal 1: [Review data available in legacy databases, e.g. mongo DB ](https://github.com/GT-ARTISAN/SMILES/issues/18)
- [ ] Goal 2: [Update data records to match the new data layout/schema](https://github.com/GT-ARTISAN/SMILES/issues/19) 
- [ ] Goal 3: [Data extraction and upload to the new database. ](https://github.com/GT-ARTISAN/SMILES/issues/20)
