### ISSUE TITLE
Establish a literature database to store predicted SMILES-based optical materials.

### ISSUE THREAD

**Issue by eroma2014** [GT-Nexus/SMILES#21]
- [ ] Goal 1: [Design the literature database user interface (UI) ](https://github.com/GT-ARTISAN/SMILES/issues/22)
- [ ] Goal 2: [Review, update, and finalize the literature database UI designs. ](https://github.com/GT-ARTISAN/SMILES/issues/23)
- [ ] Goal 3: [Develop the literature database UIs according to the design. ](https://github.com/GT-ARTISAN/SMILES/issues/24)
- [ ] Goal 4: [Implement data uploading methods to the literature database. E.g.: CSV, JSON and manual entry. ](https://github.com/GT-ARTISAN/SMILES/issues/25)
- [ ] Goal 5: [Review and publish uploaded literature data to other gateway users. ](https://github.com/GT-ARTISAN/SMILES/issues/26)
- [ ] Goal 6: [Data search implementation for literature database. ](https://github.com/GT-ARTISAN/SMILES/issues/27)
