### ISSUE TITLE
Extract materials from published literature to the literature database. 

### ISSUE THREAD

**Issue by eroma2014** [GT-Nexus/SMILES#28]
- [ ] Goal 1: [Gather and document requirement of Journal scrapping for Literature database.](https://github.com/GT-ARTISAN/SMILES/issues/3)
- [ ] Goal 2: [Add the literature extraction code to the gateway for manual runs. ](https://github.com/GT-ARTISAN/SMILES/issues/29)
- [ ] Goal 3: [Automate the extraction process through regular intervals. ](https://github.com/GT-ARTISAN/SMILES/issues/30)
- [ ] Goal 4: [Move extracted data directly to the literature database.](https://github.com/GT-ARTISAN/SMILES/issues/8)
- [ ] Goal 5: [Extend the literature extraction code.](https://github.com/GT-ARTISAN/SMILES/issues/31)
- [ ] Goal 6: [Review extracted data and publish to the gateway user.](https://github.com/GT-ARTISAN/SMILES/issues/32)
