### ISSUE TITLE
Test the code and add data to the computational environment for verification and validation.

### ISSUE THREAD

**Issue by eroma2014** [GT-Nexus/SMILES#40]
- [ ] Goal 1: [Design the computational database user interface (UI)](https://github.com/GT-ARTISAN/SMILES/issues/34)
- [ ] Goal 2: [Review, update, and finalize the computational database UI designs. ](https://github.com/GT-ARTISAN/SMILES/issues/35)
- [ ] Goal 3: [Develop the computational database UIs as per the design. ](https://github.com/GT-ARTISAN/SMILES/issues/36)
- [ ] Goal 4: [Implement data uploading methods to the database. E.g.: CSV, JSON and manual entry. ](https://github.com/GT-ARTISAN/SMILES/issues/37)
- [ ] Goal 5: [Review the computational output data and publish to other gateway users. ](https://github.com/GT-ARTISAN/SMILES/issues/38)
- [ ] Goal 6: [Data search implementation for the computational database. ](https://github.com/GT-ARTISAN/SMILES/issues/39)
